services:
  mediafilesort:
    build: ./
    volumes:
      - /Volumes/Element/hoho/Test:/app/dest
      - /Volumes/Element/hoho/Photo:/app/src
    command: 
      - python
      - media_file_sort.py
      - --mode
      - db
      - src
      - dest